API_KEY=
API_KEY_SECRET=
ACCESS_TOKEN=
ACCESS_TOKEN_SECRET=
KEYWORD=''
YYYYMMDDHH=

export API_KEY API_KEY_SECRET ACCESS_TOKEN ACCESS_TOKEN_SECRET KEYWORD YYYYMMDDHH

S3_AWS_ACCESS_KEY_ID=
S3_AWS_SECRET_ACCESS_KEY=

BUCKET_NAME=
OBJECT_KEY_PREFIX=

export S3_AWS_ACCESS_KEY_ID S3_AWS_SECRET_ACCESS_KEY BUCKET_NAME OBJECT_KEY_PREFIX
